[project]
name = "zernpy"
dynamic = ["version"]  # Discovering of the version by the setuptools (see below: in the 'file' or 'attr')
authors = [
    { name = "Sergei Klykov" },
    { email = "sergej.klykow@gmail.com" }
]
description = "Calculation of real Zernike polynomials values, associated PSFs, plotting of their profiles in polar coordinates"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
]
[project.optional-dependencies]
performance = ["numba>=0.57.1"]
dev = ["ruff", "mypy", "pytest"]
all = ["numba>=0.57.1"]

keywords = ["zernike-polynomials", "zernike-psf"]

[project.urls]  # METADATA in wheel file will represent the data below by using pip show zernpy -v
# But the links themselves are mapped / parsed by the PyPi website
"Homepage" = "https://pypi.org/project/zernpy/"
"Repository" = "https://github.com/sklykov/zernpy/"
"Bug Tracker" = "https://github.com/sklykov/zernpy/issues/"
"Documentation" = "https://sklykov.github.io/zernpy/"
"Changelog" = "https://github.com/sklykov/zernpy/blob/main/CHANGELOG.md"

[tool.setuptools.packages.find]  # Manifest.in file is only required for adding some package-data
where = ["src"]
include = ["zernpy*"]
exclude = ["zernpy.tests*"]  # only packages should be specified, folders - exclude in MANIFEST.in
namespaces = false  # forbid treating a folder as a module without explicit __init__.py presence

[tool.setuptools]
include-package-data = false  # forbid to make a confusion on the src/zernpy/tests folder presence
# confusion is produced because it is an importable module

[tool.setuptools.dynamic]
version = { attr = "zernpy.__version__" }  # Variable set in the __init__.py

[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true  # mypy will warn if any of options below not valid
warn_redundant_casts = true  # warn about unnecessary cast(): from typing import cast
warn_unused_ignores = true  # warn about unused comments '# type: ignore'
show_error_codes = true  # enables error code in a report
pretty = true  # better formatted report in a console
strict_equality = true  # checks proper usage of ==, !=, in
no_implicit_optional = true  # throws error on: def f(x: int = None): ...
# Note: flags below introduces too strict type checks
# disallow_untyped_defs = true  # all parameters and return types must be fully annotated
check_untyped_defs = true  # mypy checks untyped expressions and tries to infer types
# warn_return_any = true  # Any couldn't be used as return type
# disallow_any_generics = true  # forbid bare generics like list, dict, tuple... -> instead List[float]
exclude = [
    '^tests/',
    '^build/',
    '^dist/',
    '^src/zernpy/tests/'
]
[[tool.mypy.overrides]]  # for ignoring warning about not checked imported libraries
module = ["numba", "joblib"]
ignore_missing_imports = true
[[tool.mypy.overrides]]  # ignore found errors in the specific test files
module = [
    "zernpy.run_zernpsf_as_main",
    "zernpy.run_zernikepol_as_main"
]
ignore_errors = true

[tool.ruff]
line-length = 145  # my own preference
indent-width = 4
target-version = "py311"
[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "B", "SIM"]
ignore = ["E702", "E402", # used in the IDE
    "SIM108", # many ternany operator replacements in a code
    "SIM113", # potentially can break logic in a loop
]
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
