name: Run Python tests

on:
  push:
    branches: [ main ]  # - add for limiting it to be triggered only by pushes to the main branch
    paths:  # triggers testing action if only any Python / listed files have been changed
      - '**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/test.yaml'
  pull_request:
     branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code  # loads code from a repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
          pip install "numba>=0.57.1"

      - name: Run tests
        run: pytest
